//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba_net_2_.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int fecha { get; set; }
        public int idProducto { get; set; }
        public int idCajero { get; set; }
        public int idCliente { get; set; }
    
        public virtual Cajero Cajero { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
